name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.3.3
          virtualenvs-create: false
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false && poetry install --all-extras --no-interaction --no-ansi
      - name: Commit files and push
        env:
          CI_USER: ${{ secrets.USERNAME }}
          CI_EMAIL: ${{ secrets.EMAIL }}
          GITHUB_REPOSITORY: ${{ secrets.REPOSITORY }}
          EDITOR: true
        run: |
          if [ git diff --exit-code ]
            then
              git config --local user.email "$CI_EMAIL"
              git config --local user.name "$CI_USER"
              git commit -a --fixup HEAD
              git rebase -i HEAD~2 --autosquash
              git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master --force-with-lease
          fi
      - name: Test with pytest
        run: |
          python -m pytest --verbose --cov=geneal --cov=tests --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
